services:
  rental:
    build: .
    command: python -m services.rental
    ports: [ "8000:8000" ]
    env_file: .env
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - HTTP_BACKEND_HOST=0.0.0.0
      - HTTP_BACKEND_PORT=8000

  stubs:
    build: .
    command: python -m services.stubs
    ports: [ "3629:3629" ]

  postgres:
    image: postgres:17
    ports: [ "5432:5432" ]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/data/postgres
    volumes:
      - ./.local/pg_data:/data/postgres

  redis:
    image: redis:latest
    restart: always
    ports: [ "6379:6379" ]
    volumes:
      - ./.local/redis_data:/data
