FROM python:3.13-slim
RUN pip install pipenv

WORKDIR /app

COPY Pipfile Pipfile.lock* ./
RUN pipenv lock --python 3.13

RUN pipenv install --deploy --system

COPY . .

CMD ["python3", "-m", "pytest", "tests/unit/", "-v"]