"""init

Revision ID: 0ff055b7b9da
Revises:
Create Date: 2025-11-17 01:42:11.342510

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ff055b7b9da"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "country_retention_config",
        sa.Column(
            "country", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False
        ),
        sa.Column("retention_days", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("country"),
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "scope", sa.Enum("RENTAL_START", "OFFERS", "RENTAL_RETURN", name="idempotencykeyscope"), nullable=False
        ),
        sa.Column("request_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("response_body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "offers",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("station_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tariff_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "country", sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False
        ),
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False
        ),
        sa.Column("price_per_hour", sa.Integer(), nullable=False),
        sa.Column("free_period_min", sa.Integer(), nullable=False),
        sa.Column("deposit", sa.Integer(), nullable=False),
        sa.Column(
            "pricing_mode",
            sa.Enum("NORMAL", "FALLBACK_GREEDY", name="pricingmode"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "USED", "EXPIRED", "CANCELLED", name="offerstatus"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_offers_country"), "offers", ["country"], unique=False)
    op.create_index(op.f("ix_offers_id"), "offers", ["id"], unique=False)
    op.create_index(
        op.f("ix_offers_station_id"), "offers", ["station_id"], unique=False
    )
    op.create_index(op.f("ix_offers_user_id"), "offers", ["user_id"], unique=False)
    op.create_table(
        "rentals",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("offer_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "start_station_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "finish_station_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "country", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False
        ),
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False
        ),
        sa.Column("price_per_hour", sa.Integer(), nullable=False),
        sa.Column("free_period_min", sa.Integer(), nullable=False),
        sa.Column("deposit", sa.Integer(), nullable=False),
        sa.Column("total_amount", sa.Integer(), nullable=False),
        sa.Column("powerbank_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("finish_time", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("CREATED", "ACTIVE", "RETURNED", "CLOSED", name="rentalstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["offer_id"],
            ["offers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rentals_country"), "rentals", ["country"], unique=False)
    op.create_index(op.f("ix_rentals_id"), "rentals", ["id"], unique=False)
    op.create_index(op.f("ix_rentals_offer_id"), "rentals", ["offer_id"], unique=False)
    op.create_index(
        op.f("ix_rentals_powerbank_id"), "rentals", ["powerbank_id"], unique=False
    )
    op.create_index(op.f("ix_rentals_user_id"), "rentals", ["user_id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("order_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("AUTHORIZE", "CAPTURE", "REFUND", name="paymentkind"),
            nullable=False,
        ),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SUCCEEDED", "FAILED", name="paymentstatus"),
            nullable=False,
        ),
        sa.Column("provider_ref", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["rentals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payments_order_id"), "payments", ["order_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payments_order_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_rentals_user_id"), table_name="rentals")
    op.drop_index(op.f("ix_rentals_powerbank_id"), table_name="rentals")
    op.drop_index(op.f("ix_rentals_offer_id"), table_name="rentals")
    op.drop_index(op.f("ix_rentals_id"), table_name="rentals")
    op.drop_index(op.f("ix_rentals_country"), table_name="rentals")
    op.drop_table("rentals")
    op.drop_index(op.f("ix_offers_user_id"), table_name="offers")
    op.drop_index(op.f("ix_offers_station_id"), table_name="offers")
    op.drop_index(op.f("ix_offers_id"), table_name="offers")
    op.drop_index(op.f("ix_offers_country"), table_name="offers")
    op.drop_table("offers")
    op.drop_table("idempotency_keys")
    op.drop_table("country_retention_config")
    # ### end Alembic commands ###
