from enum import Enum


class ErrorCode(str, Enum):
    TARIFFS_STALE = "STATION_EMPTY"
    USERS_FALLBACK = "USERS_FALLBACK"
    STATION_EMPTY = "STATION_EMPTY"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    VALIDATION_ERROR = "VALIDATION_ERROR"
